# Generated by Django 3.1.7 on 2021-03-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciated', models.TextField()),
                ('available', models.BooleanField(default=False)),
                ('alternatives', models.JSONField()),
                ('correct_alternative', models.IntegerField(choices=[{0, 'a'}, {1, 'b'}, {3, 'c'}, {4, 'd'}])),
            ],
        ),
    ]
